-- One effective override per user/studio/permission. Existing deny wins;
-- otherwise retain the oldest row (id breaks timestamp ties).
DELETE FROM user_custom_permissions AS duplicate
USING user_custom_permissions AS preferred
WHERE duplicate.user_id = preferred.user_id
  AND duplicate.studio_id = preferred.studio_id
  AND duplicate.permission_id = preferred.permission_id
  AND ((duplicate.effect = 'allow' AND preferred.effect = 'deny')
    OR (duplicate.effect = preferred.effect AND
        (duplicate.created_at, duplicate.id) > (preferred.created_at, preferred.id)));
--> statement-breakpoint
CREATE UNIQUE INDEX "user_custom_permissions_identity_unique" ON "user_custom_permissions" USING btree ("user_id","studio_id","permission_id");
--> statement-breakpoint
INSERT INTO roles (code, name, is_system) VALUES
('OWNER', 'Owner', true), ('ADMIN', 'Admin', true), ('MASTER', 'Master', true), ('AI_SYSTEM', 'AI System', true)
ON CONFLICT (code) DO NOTHING;
--> statement-breakpoint
INSERT INTO permissions (code, name) VALUES
('CLIENT_READ', 'CLIENT_READ'),
('CLIENT_CREATE', 'CLIENT_CREATE'),
('CLIENT_UPDATE', 'CLIENT_UPDATE'),
('CLIENT_ARCHIVE', 'CLIENT_ARCHIVE'),
('MEDICAL_PROFILE_READ', 'MEDICAL_PROFILE_READ'),
('MEDICAL_PROFILE_UPDATE', 'MEDICAL_PROFILE_UPDATE'),
('APPOINTMENT_READ', 'APPOINTMENT_READ'),
('APPOINTMENT_CREATE', 'APPOINTMENT_CREATE'),
('APPOINTMENT_UPDATE', 'APPOINTMENT_UPDATE'),
('APPOINTMENT_CANCEL', 'APPOINTMENT_CANCEL'),
('APPOINTMENT_COMPLETE', 'APPOINTMENT_COMPLETE'),
('APPOINTMENT_NO_SHOW', 'APPOINTMENT_NO_SHOW'),
('APPOINTMENT_OVERRIDE_OVERLAP', 'APPOINTMENT_OVERRIDE_OVERLAP'),
('PROCEDURE_READ', 'PROCEDURE_READ'),
('PROCEDURE_CREATE', 'PROCEDURE_CREATE'),
('PROCEDURE_UPDATE', 'PROCEDURE_UPDATE'),
('MEDIA_READ', 'MEDIA_READ'),
('MEDIA_CREATE', 'MEDIA_CREATE'),
('CONSENT_READ', 'CONSENT_READ'),
('CONSENT_UPLOAD', 'CONSENT_UPLOAD'),
('PAYMENT_READ', 'PAYMENT_READ'),
('PAYMENT_MARK_DEPOSIT', 'PAYMENT_MARK_DEPOSIT'),
('PAYMENT_REFUND', 'PAYMENT_REFUND'),
('PAYMENT_DELETE', 'PAYMENT_DELETE'),
('FINANCE_ANALYTICS_READ', 'FINANCE_ANALYTICS_READ'),
('ANALYTICS_READ', 'ANALYTICS_READ'),
('SETTINGS_UPDATE', 'SETTINGS_UPDATE'),
('STUDIO_MANAGE', 'STUDIO_MANAGE'),
('USERS_MANAGE', 'USERS_MANAGE'),
('ROLES_MANAGE', 'ROLES_MANAGE'),
('SERVICE_READ', 'SERVICE_READ'),
('SERVICE_CREATE', 'SERVICE_CREATE'),
('SERVICE_UPDATE', 'SERVICE_UPDATE'),
('SERVICE_ARCHIVE', 'SERVICE_ARCHIVE'),
('MASTER_READ', 'MASTER_READ'),
('MASTER_CREATE', 'MASTER_CREATE'),
('MASTER_UPDATE', 'MASTER_UPDATE'),
('MASTER_ARCHIVE', 'MASTER_ARCHIVE'),
('WHATSAPP_TEMPLATE_READ', 'WHATSAPP_TEMPLATE_READ'),
('WHATSAPP_TEMPLATE_USE', 'WHATSAPP_TEMPLATE_USE'),
('WHATSAPP_TEMPLATE_MANAGE', 'WHATSAPP_TEMPLATE_MANAGE'),
('TASK_READ', 'TASK_READ'),
('TASK_CREATE', 'TASK_CREATE'),
('TASK_UPDATE', 'TASK_UPDATE'),
('REVIEW_READ', 'REVIEW_READ'),
('REVIEW_CREATE', 'REVIEW_CREATE')
ON CONFLICT (code) DO NOTHING;
--> statement-breakpoint
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'OWNER' AND p.code IN ('CLIENT_READ', 'CLIENT_CREATE', 'CLIENT_UPDATE', 'CLIENT_ARCHIVE', 'MEDICAL_PROFILE_READ', 'MEDICAL_PROFILE_UPDATE', 'APPOINTMENT_READ', 'APPOINTMENT_CREATE', 'APPOINTMENT_UPDATE', 'APPOINTMENT_CANCEL', 'APPOINTMENT_COMPLETE', 'APPOINTMENT_NO_SHOW', 'APPOINTMENT_OVERRIDE_OVERLAP', 'PROCEDURE_READ', 'PROCEDURE_CREATE', 'PROCEDURE_UPDATE', 'MEDIA_READ', 'MEDIA_CREATE', 'CONSENT_READ', 'CONSENT_UPLOAD', 'PAYMENT_READ', 'PAYMENT_MARK_DEPOSIT', 'PAYMENT_REFUND', 'PAYMENT_DELETE', 'FINANCE_ANALYTICS_READ', 'ANALYTICS_READ', 'SETTINGS_UPDATE', 'STUDIO_MANAGE', 'USERS_MANAGE', 'ROLES_MANAGE', 'SERVICE_READ', 'SERVICE_CREATE', 'SERVICE_UPDATE', 'SERVICE_ARCHIVE', 'MASTER_READ', 'MASTER_CREATE', 'MASTER_UPDATE', 'MASTER_ARCHIVE', 'WHATSAPP_TEMPLATE_READ', 'WHATSAPP_TEMPLATE_USE', 'WHATSAPP_TEMPLATE_MANAGE', 'TASK_READ', 'TASK_CREATE', 'TASK_UPDATE', 'REVIEW_READ', 'REVIEW_CREATE')
ON CONFLICT (role_id, permission_id) DO NOTHING;
--> statement-breakpoint
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'ADMIN' AND p.code IN ('CLIENT_READ', 'CLIENT_CREATE', 'CLIENT_UPDATE', 'CLIENT_ARCHIVE', 'MEDICAL_PROFILE_READ', 'APPOINTMENT_READ', 'APPOINTMENT_CREATE', 'APPOINTMENT_UPDATE', 'APPOINTMENT_CANCEL', 'APPOINTMENT_NO_SHOW', 'MEDIA_READ', 'MEDIA_CREATE', 'CONSENT_READ', 'CONSENT_UPLOAD', 'PAYMENT_READ', 'PAYMENT_MARK_DEPOSIT', 'SERVICE_READ', 'MASTER_READ', 'WHATSAPP_TEMPLATE_READ', 'WHATSAPP_TEMPLATE_USE', 'TASK_READ', 'TASK_CREATE', 'TASK_UPDATE', 'REVIEW_READ', 'REVIEW_CREATE')
ON CONFLICT (role_id, permission_id) DO NOTHING;
--> statement-breakpoint
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'MASTER' AND p.code IN ('CLIENT_READ', 'CLIENT_UPDATE', 'MEDICAL_PROFILE_READ', 'MEDICAL_PROFILE_UPDATE', 'APPOINTMENT_READ', 'APPOINTMENT_COMPLETE', 'APPOINTMENT_NO_SHOW', 'PROCEDURE_READ', 'PROCEDURE_CREATE', 'PROCEDURE_UPDATE', 'MEDIA_READ', 'MEDIA_CREATE', 'CONSENT_READ', 'CONSENT_UPLOAD', 'PAYMENT_READ', 'PAYMENT_MARK_DEPOSIT', 'SERVICE_READ', 'MASTER_READ', 'WHATSAPP_TEMPLATE_READ', 'WHATSAPP_TEMPLATE_USE', 'TASK_READ', 'TASK_CREATE', 'TASK_UPDATE', 'REVIEW_READ', 'REVIEW_CREATE')
ON CONFLICT (role_id, permission_id) DO NOTHING;
