ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_contract_check";--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "language" text;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "interested_zones" text[];--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "client_kind" text;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "reported_previous_pmu" boolean;--> statement-breakpoint
ALTER TABLE "clients" ADD COLUMN "preferred_master_id" uuid;--> statement-breakpoint
ALTER TABLE "clients" ADD CONSTRAINT "clients_preferred_master_studio_fk" FOREIGN KEY ("preferred_master_id","studio_id") REFERENCES "public"."masters"("id","studio_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_contract_check" CHECK ("audit_logs"."contract_version" = 0 or ("audit_logs"."contract_version" = 1
    and "audit_logs"."user_id" is not null and "audit_logs"."old_values" is not null and "audit_logs"."new_values" is not null
    and "audit_logs"."reason" is not null and length(trim("audit_logs"."reason")) > 0 and "audit_logs"."reason_source" is not null and "audit_logs"."reason_source" in ('user', 'command')
    and "audit_logs"."entity_type" = case "audit_logs"."action" when 'client_preferred_master_changed' then 'client' when 'master_price_changed' then 'master_price_revision' when 'offer_created' then 'offer_revision' when 'offer_revised' then 'offer_revision' when 'service_consolidated' then 'service' when 'job_recovered' then 'outbox_job' when 'client_created' then 'client' when 'client_updated' then 'client' when 'client_status_changed' then 'client' when 'client_archived' then 'client' when 'client_restored' then 'client' when 'client_master_assigned' then 'client' when 'medical_profile_updated' then 'client_medical_profile' when 'media_uploaded' then 'media' when 'media_archived' then 'media' when 'consent_uploaded' then 'consent' when 'consent_archived' then 'consent' when 'service_created' then 'service' when 'service_updated' then 'service' when 'service_archived' then 'service' when 'service_restored' then 'service' when 'master_created' then 'master' when 'master_updated' then 'master' when 'master_archived' then 'master' when 'master_restored' then 'master' when 'studio_settings_updated' then 'studio' when 'membership_changed' then 'studio_member' else '__invalid__' end
    and "audit_logs"."action" in ('client_preferred_master_changed', 'master_price_changed', 'offer_created', 'offer_revised', 'service_consolidated', 'job_recovered', 'client_created', 'client_updated', 'client_status_changed', 'client_archived', 'client_restored', 'client_master_assigned', 'medical_profile_updated', 'media_uploaded', 'media_archived', 'consent_uploaded', 'consent_archived', 'service_created', 'service_updated', 'service_archived', 'service_restored', 'master_created', 'master_updated', 'master_archived', 'master_restored', 'studio_settings_updated', 'membership_changed')));--> statement-breakpoint
ALTER TABLE "clients" ADD CONSTRAINT "clients_language_check" CHECK ("clients"."language" is null or "clients"."language" in ('it','en','ru','uk','de','fr','es','ro','pl','other'));--> statement-breakpoint
ALTER TABLE "clients" ADD CONSTRAINT "clients_kind_check" CHECK ("clients"."client_kind" is null or "clients"."client_kind" in ('new','returning'));--> statement-breakpoint
ALTER TABLE "clients" ADD CONSTRAINT "clients_interested_zones_check" CHECK ("clients"."interested_zones" is null or ("clients"."interested_zones" <@ ARRAY['brows','eyes','lips','lashes','skin']::text[] and cardinality("clients"."interested_zones") <= 5 and array_position("clients"."interested_zones", NULL) is null));